@{
    '10-CoreUtilities.ps1' = @(
        'Get-ApplicationIcon'
        'Get-StromGstLaunchCandidates'
        'Test-GstLaunchPath'
        'Normalize-GstLaunchPath'
        'Find-GstLaunch'
        'Resolve-GstLaunchSelection'
        'Find-MediaMtx'
        'Get-PathHash'
        'Ensure-UnifiedPublisherHostScript'
        'Test-DirectWebRtcUnifiedPublisherHostRequired'
        'Convert-GstLaunchArgumentsToPipelineDescription'
        'Test-CustomGstArgumentsOverride'
        'Assert-CustomGstArgumentsAreSafe'
        'Get-CustomGstArguments'
        'Get-PowerShellHostExecutable'
        'Get-UnifiedPublisherHostLaunch'
        'Get-GStreamerRuntimeFingerprint'
        'Set-GStreamerProcessEnvironmentValue'
        'Prepare-GStreamerRuntime'
        'Format-InvariantNumber'
        'Quote-GstValue'
        'Read-NewLogText'
        'Get-NearestAacBitrate'
        'Add-Label'
    )

    '11-SceneEditor.ps1' = @(
        'New-SceneNumeric'
        'Update-SceneSelectionChrome'
        'Set-SceneEditorChromeVisible'
        'Save-SceneEditorCanvasHome'
        'Restore-SceneEditorCanvasHome'
        'Resize-DynamicScenePreviewCardCanvas'
        'Show-DynamicScenePreviewInPreviewCard'
        'Update-SceneCanvasFromValues'
        'Test-ControlledLiveWorkerRunning'
        'Sync-ControlledScenePreviewProperties'
        'Push-ControlledSceneGeometryFromElement'
        'Capture-WebcamAspectRatio'
        'Set-SceneValuesFromElement'
        'Place-WebcamOnSceneCanvas'
        'Get-SelectedWebcamIndex'
        'Refresh-WebcamDevices'
        'Set-WebcamLayoutPreset'
        'Update-LiveSceneEditingGate'
        'Update-SceneUi'
        'Invoke-ScenePreviewRedraw'
        'Reset-DynamicScenePreviewFallback'
        'Resize-LiveSceneCanvas'
        'Update-SceneWorkspaceMode'
    )

    '12-MainDashboardUi.ps1' = @(
        'Apply-ModernDashboardUi'
    )

    '13-ProcessLifecycle.ps1' = @(
        'Initialize-GstJob'
        'Save-ActiveProcessState'
        'Remove-ActiveProcessState'
        'Stop-ProcessTreeById'
        'Stop-VerifiedStaleProcess'
        'Stop-StaleManagedProcesses'
        'Update-TrayMenuState'
        'Apply-StartMinimized'
        'Enforce-StartMinimizedTrayInvariant'
        'Show-MainWindow'
        'Hide-MainWindowToTray'
        'Set-WaitingForFullscreenState'
        'Scroll-LogToBottom'
        'Drain-ManagedProcessLogs'
        'Test-LogViewLive'
        'Append-Log'
        'Test-StreamStopAvailable'
        'Request-StreamStop'
        'Invoke-StreamToggle'
        'Set-RunState'
        'Test-TransportEnabled'
        'Test-StandalonePreviewAllowed'
        'Sync-StandalonePreviewState'
        'Update-MediaMtxUi'
        'Test-IsAdministrator'
    )

    '14-NetworkTuning.ps1' = @()

    '15-DefaultsReset.ps1' = @(
        'Reset-WebRtcSaneDefaults'
        'Reset-TransportDefaults'
        'Reset-VideoDefaults'
        'Reset-AudioDefaults'
        'Reset-RecordingDefaults'
        'Reset-DdnsDefaults'
        'Reset-LetsEncryptDefaults'
        'Reset-OptionsDefaults'
        'Reset-AllAppDefaults'
    )

    '16-CaptureAndAudioDevices.ps1' = @(
        'Update-TransportUi'
        'Get-SelectedCaptureMethodName'
        'Get-SelectedCaptureMethod'
        'Test-FullscreenCaptureMode'
        'Sync-LegacyFullscreenFlag'
        'Update-CaptureModeUi'
        'Resolve-FullscreenCaptureTarget'
        'Get-QueueLeakValue'
        'Get-EffectiveLiveQueueLeakValue'
        'Get-AudioTimingMode'
        'Get-WasapiClockOption'
        'Get-WasapiTimestampOption'
        'Get-WasapiSlaveMethodOption'
        'Get-WasapiLowLatencyOption'
        'Get-WasapiBufferTimeOption'
        'Get-WasapiLatencyTimeOption'
        'Get-AudioSampleRateOverrideValue'
        'Get-AudioRawCapsString'
        'Clean-GstDevicePropertyValue'
        'Get-GstDeviceMonitorPath'
        'Set-AudioDeviceComboDefaults'
        'Add-AudioDeviceComboItem'
        'Restore-AudioDeviceSelection'
        'Refresh-AudioDevices'
        'Get-SelectedWasapiDeviceOption'
        'Get-SelectedAudioDeviceId'
        'Get-AudioSourceSelectionSummary'
        'Get-WasapiSourceString'
        'Get-VideoPipelineClockMode'
        'Get-SplitAudioPipelineClockMode'
        'Get-ClockSelectIdForMode'
        'Wrap-GstPipelineWithClockSelect'
        'Get-VideoTimestampMode'
        'Get-VideoSourceTimestampOption'
        'Add-VideoSourceTimestampOption'
        'Get-VideoSyncMode'
        'Get-AudioSyncMode'
    )

    '17-DirectWebRtcPipeline.ps1' = @(
        'Test-DirectWebRtcPortRangeWorkerRequired'
        'ConvertTo-GstParseLaunchPipelineOnly'
        'Start-WebRtcPortRangeWorker'
        'Close-WebRtcPortRangeWorkerPipe'
        'Get-DirectWebRtcAvPipelineMode'
        'Test-DirectWebRtcSplitAvPipelines'
        'Get-DirectWebRtcMediaStreamGrouping'
        'Test-DirectWebRtcSeparateMediaStreams'
        'Get-DirectWebRtcMediaStreamId'
        'Get-WebRtcMediaStreamPadOptions'
        'Test-DirectWebRtcUnifiedPublisher'
        'Test-DirectWebRtcSharedSignaling'
        'Get-DirectWebRtcSplitAudioSignalingPort'
        'Get-DirectWebRtcSignalingClientHost'
        'Get-DirectWebRtcSharedSignallerUri'
        'Get-DirectWebRtcSplitAudioWsUrlForPlayer'
        'Get-DirectWebRtcSplitAudioWsUrlDescriptionForLog'
        'Get-BranchClockSyncElement'
        'Get-VideoBranchSyncSuffix'
        'Get-AudioBranchSyncSuffix'
        'Get-VideoPreviewSinkSyncOption'
        'Get-EffectiveAudioTimingSummary'
        'New-LiveQueueString'
        'Set-WebRtcRecoveryMode'
        'Get-WebRtcRecoveryFlags'
        'Apply-DirectWebRtcSmoothnessProfile'
        'Get-DirectWebRtcPacingQueue'
        'Write-DirectWebRtcWebClientConfig'
        'Set-DirectWebRtcStreamStopMarker'
        'Build-DirectWebRtcEncodedVideoBranch'
        'Get-DirectWebRtcWebServerPathSegment'
        'Get-DirectWebRtcUnifiedRtpVideoDefinition'
        'Build-DirectWebRtcUnifiedVideoBridgeArguments'
        'Build-DirectWebRtcUnifiedAudioBridgeArguments'
        'Get-DirectWebRtcStunUrlForPlayer'
        'Get-DirectWebRtcTurnUrlForPlayer'
        'Get-DirectWebRtcTurnOption'
        'Get-DirectWebRtcVideoBitrateEnvelope'
        'Build-DirectWebRtcUnifiedPublisherArguments'
        'Build-DirectWebRtcAudioOnlyArguments'
    )

    '18-ThreadingAndDebug.ps1' = @(
        'Get-CpuWorkerLimit'
        'Apply-ThreadBudget'
        'Update-GstThreadCountStatus'
        'Get-CaptureEncoderQueue'
        'Get-EffectiveAudioQueueCapMs'
        'Get-AudioInputQueue'
        'Get-AudioFinalQueue'
        'Apply-ThreadingProfile'
        'Set-GstProcessPriority'
        'Get-GstDebugSpec'
        'Test-ProcessDiskLoggingEnabled'
        'Reset-ProcessLogPaths'
        'Ensure-ProcessLogDirectory'
        'Update-GstDebugUi'
        'Set-GstTracerEnvironment'
        'Restore-GstTracerEnvironment'
        'Write-PsDebugTrace'
    )

    '19-AudioChains.ps1' = @(
        'Build-RawAudioChain'
        'Build-WhipSilentClockAudioChain'
        'Build-SyntheticSilentAudioChain'
        'Get-TimingMode'
        'Test-ClockSignalingValueEnabled'
        'Test-SendAbsoluteTimestampsEnabled'
        'Test-SplitClockSignalingOverridesActive'
        'Test-WebRtcClockSignalingForSink'
        'Get-AbsoluteTimestampTransportOption'
        'Get-AbsoluteTimestampStatusText'
        'Update-TimestampUi'
    )

    '20-WebRtcWebUi.ps1' = @(
        'Test-DirectWebRtcProtocol'
        'Test-WebRtcTransportProtocol'
        'Normalize-DirectWebRtcWebAddress'
        'Normalize-DirectWebRtcWebPath'
        'Test-DirectWebRtcWebDirectory'
        'Find-DirectWebRtcWebDirectory'
        'Get-DefaultDirectWebRtcWorkingWebDirectory'
        'Test-DirectWebRtcWebDirectoryWritable'
        'Select-DirectWebRtcFolderPath'
        'Get-DirectWebRtcWebUiVersion'
        'Compare-DirectWebRtcVersionString'
        'Get-BundledDirectWebRtcWebDirectory'
        'Get-DirectWebRtcWorkingWebDirectory'
        'Test-DirectWebRtcWebUiHasJbufStats'
        'Get-DirectWebRtcSourceWebDirectory'
        'Copy-DirectWebRtcStaticWebAssets'
        'Ensure-DirectWebRtcRuntimeWebDirectory'
        'Get-DirectWebRtcWebDirectory'
        'Get-PlayerSettingsFromUi'
        'Update-DirectWebRtcWebUiStatus'
        'Add-DirectWebRtcViewerQuery'
        'Get-DirectWebRtcViewerUrl'
        'Update-UnifiedBridgeKeyframeUi'
        'Update-DirectWebRtcUi'
    )

    '21-Recording.ps1' = @(
        'Test-RecordingEnabled'
        'Get-SelectedRecordingEncoderDefinition'
        'Get-RecordingEncoderControlSupport'
        'Get-SafeRecordingToken'
        'Resolve-RecordingFilePath'
        'Get-RecordingEncodedVideoCaps'
        'Add-CustomEncoderOptions'
        'Get-ComboSelectedOrDefault'
        'Add-NvencRateControlOptions'
        'Add-QsvRateControlOptions'
        'Get-RecordingEncoderElementChain'
        'Build-RecordingRawAudioChain'
        'Build-RecordingAudioBranch'
        'Get-RecordingBranchQueue'
        'Build-RecordingMuxPrefixAndVideoBranch'
        'Update-RecordingUi'
        'Invoke-ToggleRecording'
        'Test-RecordingFrameRateCompatible'
        'Assert-RecordingFrameRateCompatible'
    )

    '22-Encoding.ps1' = @(
        'Get-EncoderDefinitionForCombo'
        'Get-SelectedEncoderDefinition'
        'Add-EncoderFamilyOptions'
        'Get-SelectedAudioCodecDefinition'
        'Test-AudioCodecProtocolCompatibility'
        'Get-CompatibleAudioCodecNames'
        'Update-AudioCodecChoices'
        'Get-EncoderControlSupport'
        'Get-AudioEncoderChain'
        'Test-CodecProtocolCompatibility'
        'Get-CodecMediaType'
        'Get-EncodedVideoCaps'
        'Get-EncoderElementChain'
        'Update-EncoderUi'
    )

    '23-PipelineBuilders.ps1' = @(
        'Get-EffectiveCaptureSettings'
        'Build-DesktopCaptureChain'
        'Build-SceneCaptureChain'
        'Build-CaptureChain'
        'Test-PreviewEnabledForCurrentPipeline'
        'Test-PreviewVisibleNow'
        'Build-VideoBranch'
        'Build-LocalOnlyVideoPipeline'
        'Build-GstArguments'
        'Convert-GstArgumentsToPowerShellPreview'
        'Update-CommandPreview'
        'Update-ProtocolUi'
    )

    '24-Settings.ps1' = @(
        'Save-Settings'
        'Export-LabConfiguration'
        'Load-Settings'
        'Restore-SettingsFromObject'
        'Validate-Configuration'
    )

    '25-PreviewWindow.ps1' = @(
        'Ensure-PreviewParkingWindow'
        'Park-PreviewWindow'
        'Restore-PreviewWindowFromParking'
        'Reset-PreviewAppliedState'
        'Set-PreviewVisibility'
        'Try-AttachPreview'
        'Test-UseDynamicScenePreview'
        'Test-DynamicScenePreviewWanted'
        'ConvertTo-InProcessGstLaunchDescription'
        'Build-ControlledScenePreviewPipeline'
        'Close-ControlledLiveWorkerPipe'
        'Send-ControlledLiveWorkerCommand'
        'Wait-UiResponsiveTask'
        'Start-ControlledLiveWorker'
        'Test-ControlledLiveStreamRequested'
        'Start-DynamicScenePreview'
        'Stop-DynamicScenePreview'
        'Try-AttachDynamicScenePreview'
        'Test-DynamicScenePreviewAttached'
        'Invoke-DynamicScenePreviewFallback'
        'Sync-DynamicScenePreviewLayout'
        'Sync-ControlledLivePreviewLayout'
        'Restart-DynamicScenePreviewIfActive'
    )

    '26-MediaMtx.ps1' = @(
        'Read-MediaMtxStartupLogs'
        'Start-ManagedMediaMtx'
        'Stop-ManagedMediaMtx'
    )

    '27-StreamLifecycle.ps1' = @(
        'Start-GstStream'
        'Stop-ControlledLiveStream'
        'Stop-GstStream'
        'Test-GStreamerElements'
    )

    '28-PlayerConfig.ps1' = @(
        'Update-PlayerConfigFromUi'
        'Update-AudioTimingOptionUi'
    )

    '29-Cleanup.ps1' = @(
        'Invoke-ApplicationCleanup'
    )

    '30-Profiles.ps1' = @(
        'Get-BuiltInProfiles'
        'Ensure-ProfilesDirectory'
        'Get-UserProfiles'
        'Get-AllProfiles'
        'Test-ProfileProtocolCompatibility'
        'Get-CompatibleProfileNames'
        'Refresh-ProfileList'
        'Update-ProfileSelectionUi'
        'Get-CurrentSettingsSnapshot'
        'Save-ProfileAs'
        'Save-CurrentProfile'
        'Invoke-LoadSelectedProfile'
        'Remove-SelectedProfile'
        'Import-ProfileFile'
        'Export-SelectedProfile'
    )

    '31-UpnpPortForwarding.ps1' = @(
        'Get-UpnpNatDevice'
        'Get-UpnpLocalIPv4Address'
        'Test-UpnpSignalingMappedExternally'
        'Get-UpnpRequiredMappings'
        'Add-UpnpPortMappings'
        'Remove-UpnpPortMappings'
    )

    '32-Ddns.ps1' = @(
        'Get-DdnsPublicIPv4Address'
        'Get-DdnsHttpErrorDetail'
        'Resolve-CloudflareZoneId'
        'Update-DdnsRecordDuckDns'
        'Update-DdnsRecordDynV2'
        'Update-DdnsRecordCloudflare'
        'Update-DdnsRecordCustom'
        'Update-DdnsRecord'
        'Update-DdnsUi'
    )

    '33-LetsEncrypt.ps1' = @(
        'ConvertTo-AcmeBase64Url'
        'Get-LetsEncryptCertificateDirectory'
        'Set-LetsEncryptStatus'
        'Get-AcmeDirectoryUrl'
        'Get-AcmeDirectory'
        'Get-AcmeHeaderValue'
        'Get-AcmeResponseText'
        'Get-AcmeFreshNonce'
        'Get-AcmeAccountKey'
        'Get-AcmeJwk'
        'Get-AcmeJwkThumbprint'
        'Invoke-AcmeSignedRequest'
        'Get-AcmeAccountStatePath'
        'Get-AcmeAccountState'
        'Save-AcmeAccountState'
        'Register-AcmeAccount'
        'Get-AcmeDnsTxtValue'
        'Add-AcmeDnsTxtRecordCloudflare'
        'Remove-AcmeDnsTxtRecordCloudflare'
        'Add-AcmeDnsTxtRecordDuckDns'
        'Remove-AcmeDnsTxtRecordDuckDns'
        'Wait-AcmeDnsPropagation'
        'Submit-AcmeChallenge'
        'Wait-AcmeAuthorizationValid'
        'Test-LetsEncryptModernKeyAttachment'
        'New-LetsEncryptCertificateKey'
        'New-AcmeCsr'
        'Complete-AcmeOrder'
        'Get-AcmeCertificatePem'
        'Set-LetsEncryptCertificatePrivateKey'
        'Save-LetsEncryptCertificatePfx'
        'Get-LetsEncryptCertificateStatePath'
        'Get-LetsEncryptCertificateState'
        'Save-LetsEncryptCertificateState'
        'Test-LetsEncryptCertificateNeedsRenewal'
        'Update-LetsEncryptCertificate'
        'Update-LetsEncryptUi'
    )
}
